Copy CAM nosekatreport to here
ska-sa/nosekatreport pull request #1
Opened 2017-08-06 19:33 UTC by lvdheever

This is a PR to review the differences between CAM nosekatreport and CBF nosekatreport.
The CAM changes seem mostly to be improvements and additions that "should not" break CBF.
The CBF differences are specific "CBF instrument" decorators, adding matplotlib and some array specific comparison functions.

2017-08-06 19:43 UTC, lvdheever commented
@mmphego @jmanley Would you please look at this diff carefully. If we keep the "non-CBF-specific" differences (like support for matplotlib and stepBold, stepLine, and such) will you be able to manage the CBF instrument specific stuff somewhere else. [We can merge it in here for now but I would like to not leave it in here in the medium term.]

If you are reasonably happy with this suggestion, then I will update this PR to include the CBF specific stuff - which is now shown as deleted lines - and then will remove the DO NOT MERGE label once you are happy with that update.

2017-08-07 11:57 UTC, jmanley commented
Thanks Lize, that sounds reasonable. I agree that the package should not contain any CBF-specific bits. I think there are a few ways we could handle it.

How would you feel about having a separate branch for the CBF stuff?

How would you feel about having a separate CBF fork of this repository?

Jason

On 06 Aug 2017, at 21:43, Lize van den Heever <notifications@github.com> wrote:

> @mmphego @jmanley Would you please look at this diff carefully. If we keep the "non-CBF-specific" differences (like support for matplotlib and stepBold, stepLine, and such) will you be able to manage the CBF instrument specific stuff somewhere else. [We can merge it in here for now but I would like to not leave it in here in the medium term.]
> 
> If you are reasonably happy with this suggestion, then I will update this PR to include the CBF specific stuff - which is now shown as deleted lines - and then will remove the DO NOT MERGE label once you are happy with that update.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-08-07 12:32 UTC, mmphego commented
@lvdheever I think for now we can include the CBF specific stuff, In the interim I will try either one of the 3 thing.
1. Fork nosekatreport and make cbf changes in my copy and use that version for CBF (Short Term)
2. Create submodule with only CBF stuffs in it,  which would be dependent on nosekatreport
3. Add CBF directory on nosekatreport root with CBF specific stuff

What do you think?

2017-08-07 12:58 UTC, lvdheever commented
Those options sounds good. 
I will make a PR to include the CBF changes here and then we can move the "instrument" stuff out later once you have investigated the options and made a decision on how to handle it in future

2017-08-08 09:28 UTC, mmphego requested changes
@lvdheever Please see review and make changes, thereafter should be ready for a merge

2017-08-08 09:28 UTC, mmphego commented on nosekatreport/plugin.py
> -        _state.store.add_progress(message)
CBF Tests dependency, Can we uncomment for now.

2017-08-08 09:28 UTC, mmphego commented on nosekatreport/plugin.py
>                  raise TestFailed(fail_message)
This will cause a traceback, ass TestFailed class was commented out.
Uncomment TestFailed class on ln #45

2017-08-08 09:28 UTC, mmphego commented on nosekatreport/plugin.py
> +                assert _state.store.test_passed, \
Perhaps, refactor code as below (ignore indentation issues)
            try:
                fail_msg = ("\n\nNot all test steps passed\n\t"
                                "Test Name: %s\n\t"
                                "Failure Message: %s\n"%(_state.store.test_name,
                                    _state.store.error_msg))
                assert _state.store.test_passed, fail_msg
         
   except AssertionError:
                raise TestFailed(fail_message)

2017-08-08 10:10 UTC, lvdheever commented on nosekatreport/plugin.py
> +                assert _state.store.test_passed, \
Will do

2017-08-08 10:10 UTC, lvdheever commented on nosekatreport/plugin.py
>                  raise TestFailed(fail_message)
Returned TestFailed

2017-08-08 10:11 UTC, lvdheever commented on nosekatreport/plugin.py
> -        _state.store.add_progress(message)
Uncommented for now. Might want to add a command line parameter to determine whether to record the progress steps or not.

2017-08-08 10:24 UTC, mmphego commented on nosekatreport/plugin.py
> -        _state.store.add_progress(message)
Will do, when testing.

2017-08-08 10:24 UTC, mmphego approved these changes

2017-08-08 10:24 UTC, merged

2017-08-08 12:18 UTC, lvdheever commented
This branch now fails for CAM with
`AttributeError: 'StoreTestRun' object has no attribute 'test_failed'`
The reason is because I did not add test_failed to `def __init__` of `class StoreTestRun(object)`.
But now I see there is a `test_passed` already and don't want to add `test_failed`.

Why was test_failed introduced? Can we not rather use `test_passed = False`, instead of having both test_passed and test_failed?

2017-08-08 13:34 UTC, mmphego commented
Updated your PR with relevant the changes.